# Generated by Django 6.0.6 on 2026-07-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorieProject', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
